// Generated by uniffi-bindgen-react-native
#include <jni.h>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvokerHolder.h>
#include "mopro-ffi.h"

namespace jsi = facebook::jsi;
namespace react = facebook::react;

// Automated testing checks Java_com_moproffi_MoproFfiModule and moproffi
// by comparing the whole line here.
/*
Java_com_moproffi_MoproFfiModule_nativeMultiply(JNIEnv *env, jclass type, jdouble a, jdouble b) {
    return moproffi::multiply(a, b);
}
*/

// Installer coming from MoproFfiModule
extern "C"
JNIEXPORT jboolean JNICALL
Java_com_moproffi_MoproFfiModule_nativeInstallRustCrate(
    JNIEnv *env,
    jclass type,
    jlong rtPtr,
    jobject callInvokerHolderJavaObj
) {
    (void)env;
    (void)type;

    if (rtPtr == 0 || callInvokerHolderJavaObj == nullptr) {
        return false;
    }

    // React Native exposes CallInvokerHolderImpl as an fbjni HybridClass.
    // Use the supported HybridClass access pattern (cthis()) instead of reading internal Java fields.
    auto jsCallInvokerHolder = facebook::jni::make_local(
        reinterpret_cast<react::CallInvokerHolder::javaobject>(callInvokerHolderJavaObj));
    auto jsCallInvoker = jsCallInvokerHolder->cthis()->getCallInvoker();

    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return moproffi::installRustCrate(*runtime, jsCallInvoker);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_moproffi_MoproFfiModule_nativeCleanupRustCrate(JNIEnv *env, jclass type, jlong rtPtr) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return moproffi::cleanupRustCrate(*runtime);
}